Repository dtr-org/unit-e, pull requests merged in 2019-05, with the labels that each got.

#1043 Disable flaky wallet_labels test
  test/functional/test_runner.py
Labels: floating test

#1037 Factor out generate_block function
  test/functional/esperanza_slash.py
  test/functional/esperanza_slash_restart.py
  test/functional/esperanza_vote.py
  test/functional/esperanza_vote_reorg.py
  test/functional/esperanza_withdraw.py
  test/functional/feature_commits_forkchoice.py
  test/functional/feature_finalizer.py
  test/functional/feature_fork_choice_finalization.py
  test/functional/feature_fork_choice_forked_finalize_epoch.py
  test/functional/feature_fork_choice_parallel_justifications.py
  test/functional/feature_no_esperanza_tx_relay_delay.py
  test/functional/feature_reindex_commits.py
  test/functional/feature_snapshot.py
  test/functional/feature_snapshot_creation.py
  test/functional/feature_snapshot_finalization.py
  test/functional/finalization_deposit_reorg.py
  test/functional/finalization_slash_itself.py
  test/functional/finalization_state_restoration.py
  test/functional/p2p_snapshot.py
  test/functional/rpc_finalization.py
  test/functional/rpc_getblocksnapshot.py
  test/functional/test_framework/util.py
Labels: refactoring, tests

#1046 Fix compilation warnings appeared after bitcoin-0.17 merge
  src/better-enums/enum_set.h
  src/rpc/mining.cpp
  src/test/better_enum_set_tests.cpp
  src/wallet/rpcmnemonic.cpp
  src/walletinitinterface.h
Labels: technical debt

#1044 Fix wallet_multiwallet.py
  test/functional/test_framework/test_node.py
Labels: floating test

#1045 Remove absolete coins view database Upgrade logic
  src/init.cpp
  src/txdb.cpp
  src/txdb.h
Labels: technical debt

#1026 Fix incorrect mapping between dynasty and epoch
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate.h
  src/esperanza/finalizationstate_data.cpp
  src/esperanza/finalizationstate_data.h
  src/rpc/finalization.cpp
  src/test/esperanza/finalizationstate_utils.cpp
  src/test/esperanza/finalizationstate_withdraw_tests.cpp
  test/functional/esperanza_withdraw.py
  test/functional/rpc_finalization.py
  test/functional/test_framework/util.py
Labels: bug, finalization

#1049 Fix unit test: util_tests_datadir/test_LockDirectory
  src/test/util_tests.cpp
Labels: broken test, tests

#1040 Validate deposit prior adding to the wallet
  src/esperanza/walletextension.cpp
  test/functional/esperanza_admin_full_cycle.py
Labels: bug, wallet

#1048 Fix wallet_labels.py
  test/functional/test_runner.py
  test/functional/wallet_labels.py
Labels: floating test

#1047 Fix GCC warnings in prevector.h by initializing class fields
  src/prevector.h
Labels: build

#1052 Increase the max line length for pep8speaks to 120 characters
  .pep8speaks.yml
Labels: repo

#1059 Fix sources for git subtrees
  test/lint/README.md
Labels: upstream sync

#1065 Reduce Travis log spam
  src/Makefile.test.include
Labels: tests

#1063 Remove duplicate tests and add check
  test/functional/test_runner.py
Labels: tests

#1067 Add GetName to staking wallet
  src/esperanza/walletextension.cpp
  src/esperanza/walletextension.h
  src/staking/stakingwallet.h
  src/test/proposer/block_builder_tests.cpp
Labels: feature

#1061 Set epochLength=200 in feature_assumevalid.py
  test/functional/feature_assumevalid.py
Labels: tests

#1058 Add IsMineStkeable test for output types
  src/test/ismine_tests.cpp
Labels: tests

#1070 Remove function without implementation from LegacyValidationInterface
  src/staking/legacy_validation_interface.h
Labels: refactoring, technical debt

#1066 Minor adjustments for the tests and codestyle
  src/esperanza/walletextension.cpp
  src/test/mempool_tests.cpp
  src/usbdevice/rpcusbdevice.cpp
  test/functional/p2p_fingerprint.py
Labels: refactoring

#1071 Convert two fields of FinalizationState to local variables
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate_data.cpp
  src/esperanza/finalizationstate_data.h
  src/test/esperanza/finalizationstate_utils.cpp
Labels: finalization

#1051 New RPC propose and proposetoaddress
  src/injector.h
  src/miner.cpp
  src/proposer/block_builder.cpp
  src/proposer/block_builder.h
  src/proposer/proposer.cpp
  src/proposer/proposer.h
  src/proposer/proposer_logic.cpp
  src/proposer/proposer_rpc.cpp
  src/proposer/proposer_rpc.h
  src/rpc/parameter_conversion.cpp
  src/rpc/proposing.cpp
  src/staking/block_validator.cpp
  src/test/esperanza/walletextension_tests.cpp
  src/test/proposer/block_builder_tests.cpp
  src/test/proposer/proposer_tests.cpp
  test/functional/proposer_settings.py
  test/functional/proposer_stake_maturity.py
  test/functional/rpc_propose.py
  test/functional/test_runner.py
Labels: feature, technical debt

#1074 Rename functional tests
  test/functional/README.md
  test/functional/feature_no_vote_tx_relay_delay.py
  test/functional/finalization_admin_full_cycle.py
  test/functional/finalization_admin_validation.py
  test/functional/finalization_deposit.py
  test/functional/finalization_deposit_reorg.py
  test/functional/finalization_expired_vote_conflict.py
  test/functional/finalization_finalizationstate.py
  test/functional/finalization_logout.py
  test/functional/finalization_slash.py
  test/functional/finalization_slash_restart.py
  test/functional/finalization_vote.py
  test/functional/finalization_vote_reorg.py
  test/functional/finalization_withdraw.py
  test/functional/test_runner.py
Labels: refactoring

#1077 Remove fCheckDuplicateInputs flag from CheckTransaction
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/staking/legacy_validation_interface.cpp
Labels: refactoring, security

#1069 Update copyright headers
  contrib/devtools/circular-dependencies.py
  contrib/devtools/copyright_header.py
  contrib/devtools/test_copyright_header.py
  contrib/filter-lcov.py
  src/blockchain/regtest_funds.cpp
  src/blockchain/testnet_funds.cpp
  src/finalization/state_processor.cpp
  src/staking/block_validation_info.cpp
  src/staking/block_validation_info.h
  src/staking/validation_error.cpp
  src/staking/validation_error.h
  src/staking/validation_result.cpp
  src/staking/validation_result.h
  src/trit.cpp
  test/functional/feature_graphene_active.py
  test/functional/feature_remote_staking.py
  test/functional/p2p_embargoman_star.py
  test/functional/proposer_remote_staking.py
  test/functional/test_framework/blockstore.py
Labels: documentation, tools

#1080 Use fixture templates to allow running same tests on different implementations
  src/test/validation_tests.cpp
Labels: tests

#1072 scripted-diff: Update year in copyright headers
  contrib/devtools/lint-clang-format.py
  src/better-enums/enum_set.h
  src/blockchain/blockchain_genesis.h
  src/blockchain/blockchain_interfaces.h
  src/dependency_injector.h
  src/esperanza/admincommand.cpp
  src/esperanza/admincommand.h
  src/esperanza/adminparams.h
  src/esperanza/checkpoint.cpp
  src/esperanza/checkpoint.h
  src/esperanza/checks.h
  src/esperanza/init.cpp
  src/esperanza/validator.cpp
  src/esperanza/validator.h
  src/esperanza/validatorstate.h
  src/esperanza/vote.cpp
  src/esperanza/vote.h
  src/finalization/vote_recorder.cpp
  src/finalization/vote_recorder.h
  src/proposer/proposer_state.h
  src/proposer/waiter.cpp
  src/proposer/waiter.h
  src/rpc/finalization.cpp
  src/rpc/proposing.h
  src/settings.cpp
  src/snapshot/chainstate_iterator.cpp
  src/snapshot/chainstate_iterator.h
  src/snapshot/creator.h
  src/snapshot/snapshot_index.cpp
  src/test/better_enum_set_tests.cpp
  src/test/dependency_injector_tests.cpp
  src/test/esperanza/adminstate_tests.cpp
  src/test/esperanza/finalization_utils.cpp
  src/test/esperanza/finalization_utils.h
  src/test/esperanza/finalizationstate_utils.cpp
  src/test/esperanza/finalizationstate_utils.h
  src/test/finalization/vote_recorder_tests.cpp
  src/test/interpreter_tests.cpp
  src/test/sign_tests.cpp
  src/test/snapshot/chainstate_iterator_tests.cpp
  src/test/snapshot/creator_tests.cpp
  src/test/staking/stake_validator_tests.cpp
  src/test/ufp64_tests.cpp
  src/wallet/rpcaddressbook.cpp
  src/wallet/rpcadmin.cpp
  src/wallet/test/rpcvalidator_tests.cpp
  test/functional/feature_graphene_passive.py
  test/functional/feature_spend_genesis.py
  test/functional/finalization_finalizationstate.py
  test/functional/p2p_embargoman_star.py
  test/functional/proposer_balance.py
  test/functional/proposer_multiwallet.py
  test/functional/proposer_settings.py
  test/functional/proposer_stakeable_balance.py
  test/functional/rpc_runstringcommand.py
  test/functional/rpc_sendtypeto.py
  test/functional/test_framework/regtest_mnemonics.py
  test/functional/wallet_importmasterkey.py
Labels: documentation

#1084 Fix scripted diffs with CRs in the commit message
  test/lint/commit-script-check.sh
Labels: ci

#1079 Re-enable lint checks
  .travis/lint_06_script.sh
  contrib/cmake/gen-cmakelists.sh
  contrib/devtools/camel_to_snake.py
  contrib/devtools/run-functional-tests.sh
  contrib/devtools/run-unit-tests.sh
  contrib/devtools/test_copyright_header.py
  contrib/test_gitian-build.py
  contrib/verifybinaries/verify.sh
  src/chain.h
  src/consensus/tx_verify.cpp
  src/esperanza/finalizationstate.cpp
  src/esperanza/walletextension.cpp
  src/finalization/vote_recorder.cpp
  src/finalization/vote_recorder.h
  src/leveldb/CONTRIBUTING.md
  src/leveldb/WINDOWS.md
  src/miner.cpp
  src/net_processing.cpp
  src/rpc/util.h
  src/script/interpreter.cpp
  src/secp256k1/src/modules/multiset/README.md
  src/snapshot/snapshot_index.h
  src/sync.cpp
  src/test/esperanza/checks_tests.cpp
  src/test/esperanza/finalizationstate_utils.h
  src/test/finalization/vote_recorder_tests.cpp
  src/test/interpreter_tests.cpp
  src/test/sign_tests.cpp
  src/test/staking/stake_validator_tests.cpp
  src/test/ufp64_tests.cpp
  src/validation.cpp
  src/wallet/rpcadmin.cpp
  src/wallet/wallet.cpp
  test/functional/finalization_expired_vote_conflict.py
  test/lint/lint-all.sh
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-includes.sh
  test/lint/lint-locale-dependence.sh
  test/lint/lint-shell-locale.sh
Labels: tests

#1085 Fix some comments
  src/coins.h
  test/functional/feature_snapshot_finalization.py
Labels: style

#1076 Run unit tests of Python scripts in contrib/
  .travis/lint_04_install.sh
  .travis/lint_06_script.sh
  contrib/test_data/gitian_build/test_setup_linux.log.expected
  contrib/test_data/gitian_build/test_setup_mac.log.expected
Labels: ci

#1087 Move GetEpoch, IsEpochStart, and IsCheckpoint to finalization::Params
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate.h
  src/finalization/params.h
  src/test/esperanza/finalizationstate_tests.cpp
  src/test/finalization/params_tests.cpp
Labels: refactoring

#1086 Removes a piece of dead code
  test/functional/test_framework/blocktools.py
  test/functional/wallet_listsinceblock.py
Labels: refactoring

#1083 Cleanup old checkpoints from finalization state
  src/esperanza/finalizationstate.cpp
  src/test/esperanza/checks_tests.cpp
  src/test/esperanza/finalizationstate_vote_tests.cpp
  test/functional/finalization_vote.py
Labels: finalization

#1090 Enable lint-python.sh for functional tests
  .pep8speaks.yml
  contrib/devtools/clang-format-diff.py
  contrib/devtools/copyright_header.py
  contrib/devtools/lint-clang-format.py
  contrib/devtools/lint-newline-at-eof.py
  contrib/devtools/run-functional-tests.sh
  contrib/devtools/symbol-check.py
  contrib/gitian-build.py
  contrib/linearize/linearize-data.py
  contrib/linearize/linearize-hashes.py
  contrib/seeds/generate-seeds.py
  contrib/test_gitian-build.py
  test/functional/feature_assumevalid.py
  test/functional/feature_bip68_sequence.py
  test/functional/feature_cltv.py
  test/functional/feature_csv_activation.py
  test/functional/feature_fork_choice_finalization.py
  test/functional/feature_fork_choice_parallel_justifications.py
  test/functional/feature_graphene_passive.py
  test/functional/feature_help.py
  test/functional/feature_logging.py
  test/functional/feature_ltor.py
  test/functional/feature_nulldummy.py
  test/functional/feature_reindex_commits.py
  test/functional/feature_remote_staking.py
  test/functional/feature_snapshot_creation.py
  test/functional/feature_staking.py
  test/functional/feature_uacomment.py
  test/functional/finalization_state_restoration.py
  test/functional/mining_prioritisetransaction.py
  test/functional/p2p_commits.py
  test/functional/p2p_compactblocks.py
  test/functional/p2p_fingerprint.py
  test/functional/p2p_segwit.py
  test/functional/p2p_unrequested_blocks.py
  test/functional/proposer_settings.py
  test/functional/proposer_stakeable_balance.py
  test/functional/rpc_filtertransactions.py
  test/functional/rpc_scantxoutset.py
  test/functional/rpc_sendtypeto.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/mininode.py
  test/functional/test_framework/segwit_addr.py
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
  test/functional/wallet_bumpfee.py
  test/functional/wallet_labels.py
  test/functional/wallet_multiwallet.py
  test/functional/wallet_txn_clone.py
  test/lint/check-doc.py
  test/lint/check-rpc-mappings.py
  test/lint/lint-all.sh
  test/lint/lint-format-strings.py
Labels: brainstorming, ci

#1091 Pull reminders badge
  README.md
Labels: documentation

#1088 Uniform Mocks + Blocktool for faking block index
  src/Makefile.test.include
  src/test/finalization/state_db_tests.cpp
  src/test/finalization/state_processor_tests.cpp
  src/test/finalization/state_repository_tests.cpp
  src/test/finalizer_commits_handler_tests.cpp
  src/test/proposer/proposer_logic_tests.cpp
  src/test/proposer/proposer_tests.cpp
  src/test/staking/stake_validator_tests.cpp
  src/test/test_unite_mocks.h
  src/test/tx_verify_tests.cpp
  src/test/util/blocktools.cpp
  src/test/util/blocktools.h
  src/test/util/blocktools_tests.cpp
  src/test/util/mocks.cpp
  src/test/util/mocks.h
  src/wallet/test/wallet_test_fixture.cpp
Labels: tests

#1075 Restore unit test keepalives in Travis
  .travis/test_06_script.sh
  test/util/unite-util-test.py
Labels: ci

#1094 Remove check_proof_of_work flag
  src/staking/legacy_validation_interface.cpp
  src/staking/legacy_validation_interface.h
  src/test/validation_tests.cpp
  src/validation.cpp
Labels: refactoring, technical debt

#1097 Build active chain while reindexing blocks on disk
  src/validation.cpp
Labels: resource usage

#1082 Finalize the latest epoch
  src/Makefile.test.include
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate.h
  src/finalization/state_processor.cpp
  src/finalization/state_repository.cpp
  src/test/esperanza/checks_tests.cpp
  src/test/esperanza/finalizationstate_calculate_withdraw_amount_tests.cpp
  src/test/esperanza/finalizationstate_deposit_tests.cpp
  src/test/esperanza/finalizationstate_logout_tests.cpp
  src/test/esperanza/finalizationstate_slash_tests.cpp
  src/test/esperanza/finalizationstate_tests.cpp
  src/test/esperanza/finalizationstate_utils.cpp
  src/test/esperanza/finalizationstate_utils.h
  src/test/esperanza/finalizationstate_vote_tests.cpp
  src/test/esperanza/finalizationstate_withdraw_tests.cpp
  src/test/finalization/state_processor_tests.cpp
  src/test/finalization/state_repository_tests.cpp
  src/validation.cpp
  test/functional/feature_commits_forkchoice.py
  test/functional/feature_finalizer.py
  test/functional/feature_fork_choice_finalization.py
  test/functional/feature_fork_choice_forked_finalize_epoch.py
  test/functional/feature_fork_choice_parallel_justifications.py
  test/functional/feature_reindex_commits.py
  test/functional/feature_snapshot.py
  test/functional/feature_snapshot_creation.py
  test/functional/feature_snapshot_finalization.py
  test/functional/finalization_deposit.py
  test/functional/finalization_deposit_reorg.py
  test/functional/finalization_expired_vote_conflict.py
  test/functional/finalization_logout.py
  test/functional/finalization_slash.py
  test/functional/finalization_slash_itself.py
  test/functional/finalization_slash_restart.py
  test/functional/finalization_state_restoration.py
  test/functional/finalization_vote.py
  test/functional/finalization_vote_reorg.py
  test/functional/finalization_withdraw.py
  test/functional/mempool_resurrect.py
  test/functional/p2p_commits.py
  test/functional/p2p_snapshot.py
  test/functional/rpc_finalization.py
  test/functional/rpc_preciousblock.py
Labels: bug, finalization

#1093 Block reward validation
  src/Makefile.am
  src/Makefile.test.include
  src/consensus/tx_verify.cpp
  src/injector.h
  src/staking/block_reward_validator.cpp
  src/staking/block_reward_validator.h
  src/test/staking/block_reward_validator_tests.cpp
  src/test/tx_verify_tests.cpp
  src/validation.cpp
Labels: consensus

#1089 TestChain100Setup: Replace BlockAssembler with BlockBuilder
  src/test/esperanza/walletextension_tests.cpp
  src/test/txvalidationcache_tests.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/test/wallet_test_fixture.h
  src/wallet/test/wallet_tests.cpp
Labels: tests

#1100 Fix feature_commits_forkchoice
  test/functional/feature_commits_forkchoice.py
Labels: floating test

#1101 Restore linters missed when merging bitcoin 0.17
  .travis/test_04_install.sh
  doc/descriptors.md
  test/lint/lint-all.sh
  test/lint/lint-clang-format.py
  test/lint/lint-newline-at-eof.py
  test/lint/lint-python.sh
  test/lint/lint-shebang.sh
  test/lint/shared/__init__.py
  test/lint/shared/lib.py
Labels: ci, tests

#1098 Simplify BlockValidationResult
  src/staking/block_validator.cpp
  src/staking/block_validator.h
  src/staking/stake_validator.cpp
  src/staking/validation_error.cpp
  src/staking/validation_result.cpp
  src/staking/validation_result.h
  src/test/proposer/block_builder_tests.cpp
  src/test/staking/abstract_block_validator_tests.cpp
  src/test/staking/block_validator_tests.cpp
  src/test/staking/stake_validator_tests.cpp
  src/test/test_unite_mocks.h
  src/validation.cpp
Labels: refactoring

#1103 Fix pre-commit hook
  contrib/githooks/pre-commit
Labels: tools

#1102 Fix compilation warning
  src/test/staking/block_reward_validator_tests.cpp
Labels: tests

#1099 Use proper meta input prevout
  src/proposer/block_builder.cpp
  src/staking/block_validator.cpp
  src/staking/validation_error.cpp
  src/staking/validation_error.h
  src/test/staking/block_validator_tests.cpp
  test/functional/data/rpc_getblockstats.json
Labels: bug

#1107 Remove dead code in Esperanza-related files
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate.h
  src/esperanza/walletextension.h
Labels: technical debt

#1106 Create New Impl for Validation
  src/Makefile.am
  src/Makefile.test.include
  src/amount.h
  src/blockchain/blockchain_behavior.cpp
  src/blockchain/blockchain_behavior.h
  src/blockchain/blockchain_custom_parameters.cpp
  src/blockchain/blockchain_parameters.cpp
  src/blockchain/blockchain_parameters.h
  src/blockchain/blockchain_rpc.cpp
  src/consensus/validation.h
  src/injector.h
  src/staking/block_validator.cpp
  src/staking/block_validator.h
  src/staking/legacy_validation_interface.cpp
  src/staking/legacy_validation_interface.h
  src/staking/validation_error.cpp
  src/staking/validation_error.h
  src/test/blockchain/blockchain_behavior_tests.cpp
  src/test/proposer/block_builder_tests.cpp
  src/test/staking/abstract_block_validator_tests.cpp
  src/test/staking/block_validator_tests.cpp
  src/test/test_unite_mocks.h
  src/test/util/txtools.cpp
  src/test/util/txtools.h
  src/test/util/util.cpp
  src/test/util/util.h
  src/test/validation_tests.cpp
  test/functional/mempool_accept.py
Labels: refactoring

#1108 Move security policy to own file
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation, repo

#1114 Fix dead link in the docs for the clang-format git hook
  doc/developer-notes.md
Labels: documentation

#1111 Remove unused code
  src/validation.h
Labels: technical debt

#1113 Remove arguments that are not required
  src/blockdb.cpp
  src/index/base.cpp
  src/net_processing.cpp
  src/p2p/finalizer_commits_handler_impl.cpp
  src/p2p/graphene_sender.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/rawtransaction.cpp
  src/snapshot/rpc_processing.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/zmq/zmqpublishnotifier.cpp
Labels: refactoring, technical debt
