Repository dtr-org/unit-e, pull requests merged in 2019-04, with the labels that each got.

#1004 Change TxType type from uint16_t to uint8_t
  src/primitives/txtype.h
Labels: technical debt

#1005 Use RPC to vote on parallel chain
  test/functional/feature_fork_choice_forked_finalize_epoch.py
  test/functional/test_framework/util.py
Labels: finalization, floating test

#1016 Return transaction finalization state in filtertransactions
  src/wallet/rpcwalletext.cpp
  src/wallet/test/rpcwalletext_tests.cpp
Labels: feature

#1012 Make finalization params injectable
  src/Makefile.am
  src/Makefile.test.include
  src/chainparams.cpp
  src/chainparams.h
  src/esperanza/finalizationparams.cpp
  src/esperanza/finalizationparams.h
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate.h
  src/finalization/params.cpp
  src/finalization/params.h
  src/finalization/state_db.cpp
  src/finalization/state_db.h
  src/finalization/state_processor.cpp
  src/finalization/state_processor.h
  src/finalization/state_repository.cpp
  src/finalization/state_repository.h
  src/init.cpp
  src/injector.h
  src/injector_config.h
  src/rpc/finalization.cpp
  src/test/esperanza/checks_tests.cpp
  src/test/esperanza/finalizationparams_tests.cpp
  src/test/esperanza/finalizationstate_deposit_tests.cpp
  src/test/esperanza/finalizationstate_logout_tests.cpp
  src/test/esperanza/finalizationstate_slash_tests.cpp
  src/test/esperanza/finalizationstate_tests.cpp
  src/test/esperanza/finalizationstate_utils.h
  src/test/esperanza/finalizationstate_vote_tests.cpp
  src/test/esperanza/finalizationstate_withdraw_tests.cpp
  src/test/esperanza/walletextension_tests.cpp
  src/test/finalization/params_tests.cpp
  src/test/finalization/state_db_tests.cpp
  src/test/finalization/state_processor_tests.cpp
  src/test/finalization/state_repository_tests.cpp
  src/test/finalization/vote_recorder_tests.cpp
  src/test/finalizer_commits_handler_tests.cpp
  src/test/serialize_tests.cpp
  src/test/test_unite.cpp
  src/test/test_unite.h
  src/test/test_unite_mocks.h
  src/test/validation_block_tests.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/test/wallet_test_fixture.h
Labels: finalization, refactoring

#1010 Fix proposer_stakeable_balance.py
  test/functional/proposer_stakeable_balance.py
Labels: floating test

#1019 Reduce circular dependencies in esperanza
  src/Makefile.am
  src/esperanza/checks.cpp
  src/esperanza/checks.h
  src/esperanza/finalizationstate.cpp
  src/esperanza/script.cpp
  src/esperanza/script.h
  src/esperanza/walletextension.cpp
  src/test/esperanza/checks_tests.cpp
Labels: refactoring, technical debt

#1022 Eliminate timing issue with the node syncing in example_test.py
  test/functional/example_test.py
Labels: backport, floating test

#1008 Add some missing copyright notices
  src/primitives/block.cpp
  src/primitives/block.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/primitives/txtype.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: documentation

#1018 Add test cases for esperanza commits in transaction_tests
  src/test/data/tx_invalid.json
  src/test/data/tx_valid.json
  src/test/transaction_tests.cpp
  test/functional/feature_remote_staking.py
Labels: tests

#1021 Remove links to the outdated spec
  README.md
Labels: documentation

#1024 Show failing unit tests at the bottom in run-unit-tests.sh
  contrib/devtools/run-unit-tests.sh
Labels: tools

#1015 Workaround for issue 962
  src/wallet/wallet.cpp
Labels: logs

#1028 update help message for getblockheader and getblock (#963)
  src/rpc/blockchain.cpp
Labels: rpc, usability

#1029 Serialize witness blocks in msg_block always
  test/functional/feature_assumevalid.py
  test/functional/feature_bip68_sequence.py
  test/functional/feature_fork_choice_parallel_justifications.py
  test/functional/feature_graphene_active.py
  test/functional/feature_nulldummy.py
  test/functional/feature_remote_staking.py
  test/functional/p2p_compactblocks.py
  test/functional/p2p_invalid_stake.py
  test/functional/p2p_segwit.py
  test/functional/p2p_snapshot.py
  test/functional/p2p_unrequested_blocks.py
  test/functional/proposer_stake_maturity.py
  test/functional/test_framework/blocktools.py
  test/functional/test_framework/comptool.py
  test/functional/test_framework/messages.py
  test/functional/wallet_bumpfee.py
  test/functional/wallet_importmasterkey.py
Labels: tests

#1030 Make formatting of RPC commands consistent
  src/wallet/rpcwalletext.cpp
Labels: documentation, usability

#1031 Speedup feature_commits_forkchoice.py
  test/functional/feature_commits_forkchoice.py
Labels: refactoring, tests

#1009 Fix inconsistent ValidatorState after reorgs
  src/esperanza/finalizationstate.cpp
  src/esperanza/finalizationstate.h
  src/esperanza/validator.cpp
  src/esperanza/validator.h
  src/esperanza/validatorstate.h
  src/esperanza/walletextension.cpp
  src/esperanza/walletextension.h
  src/test/esperanza/finalizationstate_withdraw_tests.cpp
  src/wallet/rpcvalidator.cpp
  test/functional/esperanza_deposit.py
  test/functional/esperanza_logout.py
  test/functional/esperanza_withdraw.py
  test/functional/finalization_deposit_reorg.py
  test/functional/test_runner.py
Labels: bug, finalization, wallet

#1036 Functional tests witness messages follow up
  test/functional/p2p_compactblocks.py
  test/functional/p2p_segwit.py
  test/functional/test_framework/blockstore.py
  test/functional/test_framework/messages.py
Labels: tests

#1035 Adjust types in CBloomFilter
  src/bloom.cpp
  src/bloom.h
Labels: technical debt

#1034 Add check for the genesis block's supply
  src/blockchain/blockchain_parameters.cpp
Labels: refactoring
